service: learn-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  memorySize: 512
  timeout: 10
  stage: prod
  environment:
    JWT_SECRET: sercretKey
    JWT_EXPIRES_IN: 1h
    REGION: eu-north-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:eu-north-1:*:table/Users

        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:eu-north-1:*:table/Students

        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:eu-north-1:*:table/Trainers

        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:eu-north-1:*:table/Specializations

        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: arn:aws:dynamodb:eu-north-1:*:table/Subscriptions

        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:eu-north-1:*:table/TrainerToStudent

        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:eu-north-1:*:table/TrainingTypes

        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:PutItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:eu-north-1:*:table/Trainings

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
        - http://learnapp-frontend-prod.s3-website.eu-north-1.amazonaws.com
        - https://cloudfront-url.com
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      allowCredentials: true

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-s3-sync
  - serverless-esbuild

custom:
  s3Sync:
    - bucketName: learn-app-frontend-bucket-${self:provider.stage}
      localDir: ../frontend/build

  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
      - '@nestjs/microservices'
      - '@nestjs/microservices/microservices-module'
      - '@nestjs/websockets/socket-module'
      - '@fastify/static'

package:
  individually: true
  exclude:
    - node_modules/**
    - test/**
    - frontend/**
    - src/**
    - "**/*.ts"