service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    DYNAMODB_USER_TABLE: user-table
    REGION: ${env:REGION}
    # etc.

functions:
  user:
    handler: src/user/user.controller
    events:
      - http:
          path: users
          method: get
      - http:
          path: users
          method: post
      # etc.

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  individually: true

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
